meson: install symlink
After installing libxml2, header files are in `/usr/include/libxml2/libxml` not in `/usr/include/libxml` and this causes fatal error while compilation, e.g. 
```
fatal error: 'libxml/parser.h' file not found
 #include <libxml/parser.h>
                 ^~~~~~~~~~~
```